name: Run TF checks on directory

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  root_account:
    uses: gnublin/php-test/.github/workflows/tf_checks.yml@main
    with:
      environment: "terraform"