name: Run TF checks

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      working_dir:
        description: 'Terraform working directory'
        required: true
        type: string

jobs:
  TerraformChecks:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    defaults:
      run:
        working-directory: ${{ github.event.inputs.working_dir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
